### ISSUE TITLE
Blog Project Plan

### ISSUE THREAD

**Issue by sazhu24** [stat231-f21/blog_giRlbosses#1]
1. Do you plan for your final project to be an extension of the mid-semester project?

Our final project will be an extension of the mid-semester project, but looking at sustainability more broadly at Amherst and colleges on a national level. We will conduct sentiment analysis on the Amherst sustainability report that we have already scraped (text analysis). We will also dive deeper into the STARS (Sustainability Tracking, Assessment & Rating System) database for colleges/universities across the US to develop a better framework for understanding progress and innovation in sustainability across higher education. We will specifically compare sustainability in academics and institutional engagement, as well as energy efficiency, waste production levels, and sustainable dining and purchasing practices. We will then create an interactive map to visualize growth and patterns geographically. We hope this feature will help foster collaboration by bridging the gap between neighboring institutions, highlighting innovative practices, and holding institutions accountable.

2. Describe what you hope to deliver as a final product. Will your blog include a published Shiny application? Will it incorporate an interactive map? Will it involve a predictive model that forecasts future values of some quantity using data that you’ve integrated?

Our blog hopes to examine how the discussion around sustainability on the Amherst campus is articulated and also how it has changed over time, as well as examining sustainability in colleges at a national level. Our blog will include a published Shiny application with an interactive map of US colleges navigating different aspects of each institution's STAR report card, and a post about the findings from our sentiment analysis.

3. Outline a schedule for your group’s progress that will take you from now (ideas phase) to final blog post and presentation at the end of the semester. During the last project, we had specific checkpoints for different phases of the project. Based on what you envision for your final blog post, identify checkpoints for your group and dates by which you plan to reach those checkpoints. Hold each other accountable, so you’re not waiting until the last minute to do things! In particular, you should have at least one checkpoint each week (ideally two) identifying what work you expect to complete by then.

Gillian - Sentiment Analysis, Hannah - Interactive Map, Sara - STAR Report Analysis

November 9:
All New Data Wrangled -
Hannah: Dataset with Sustainability in Colleges by State
Sara: STAR Report Database Wrangled
Gillian: Start Sentiment Analysis

November 16:
All Separate Aspects Finished -
Hannah: Interactive Map
Sara: Interactive Map with Report Card Analysis by College
Gillian: Sentiment Analysis

November 18:
Write-Up Finished
Meet to Practice Presentation

November 23: Thanksgiving Break

November 30:
Presentation

December 8:
Final Blog Due

**Comment by bebailey** [comment]
Sounds like a good plan! 

---

To embed a shiny app, you can use a code chunk (see [this link](https://bookdown.org/yihui/bookdown/web-pages-and-shiny-apps.html) for details):

```
knitr::include_app("https://your-account.shinyapps.io/your-app/", height = "600px")
```

**Comment by grichard24** [comment]
We're right on schedule! 

Hannah: Scraped lots of data on sustainability studies degrees awarded for 974 schools nationwide, tuition costs, degrees awarded by county, growth of degrees awarded by county, top 30 sustainability schools and annual green power usage

Sara: Scraped STARS database for all schools and individual scores for each component and mapped with rating on an interactive map

Gillian: Started sentiment analysis (word frequency, word cloud, nrc lexicon)

**Comment by grichard24** [comment]
We're still roughly on schedule. We all finished (or almost) our individual components. Our plan is to work on putting everything together and starting the write-up in class on Thursday because we all have busy weeks/exams this week. After class on Thursday, we will assign everyone parts to finish up the write-up by the time we come back from break. We will meet on November 29 instead of the 18 to practice our presentation.

Hannah: I created a leaflet map of sustainability studies degrees awarded for 500 universities across the nation and need to edit the degrees so it’s number of degrees over number of students. I finished a map and just need to add a few components.

Sara: I’m close but still want to add a few more interactive features to the map like a search bar and popup info to the Shiny app.

Gillian: I finished the sentiment analysis. It has a word frequency visualization, word cloud, NRC Lexicon visualization, AFINN Lexicon visualization, and BING Lexicon Visualization.
